/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package control_salones.vista;

import control_salones.controlador.Carrera_modulocontrolador;
import control_salones.modelo.Carrera_Modulo;
import java.util.ArrayList;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EFI
 */
public class frm_Modulos extends javax.swing.JFrame {

    /**
     * Creates new form frm_Modulos
     */
    public frm_Modulos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblModulo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblModulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblModulo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 780, 316));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
       Modulos();
    }//GEN-LAST:event_formWindowGainedFocus
public void Modulos() {
       //definir nombres de columna
        Object [] cols = {  "codigo especialidad", "evento", "tipo evento", "nivel competencia", "duracion", "estado", "carrera"};
        //crear arrayList
      ArrayList<Carrera_Modulo> miLista = new ArrayList<Carrera_Modulo>();
      Carrera_modulocontrolador control = new Carrera_modulocontrolador();
      frm_Carrera modulo = new frm_Carrera();
      miLista = control.ConsultarModulo(modulo.codigo);
      tblModulo.getModel();
      //creamos Object para agregar las filas de datos 
      Object[][] data = new Object[miLista.size()][cols.length];
        int rowCount = 0;
        for(Carrera_Modulo c : miLista){
          
            data[rowCount][0] = c.getCodigo_especialidad();
            data[rowCount][1] = c.getNombre_evento();
            data[rowCount][2] = c.getTipo_evento();
             data[rowCount][3] = c.getNivel_competencia();
              data[rowCount][4] = c.getDuracion_modulo();
               data[rowCount][5] = c.getEstado_modulo();
               data[rowCount][6] = c.getNombre_carrera();
            rowCount++;
        }
        DefaultTableModel model = new DefaultTableModel(data, cols);
        tblModulo.setModel(model);
        
        model.addTableModelListener(new TableModelListener() {
         @Override
         public void tableChanged(TableModelEvent e) {
             System.out.println(tblModulo.getModel().getValueAt(tblModulo.getSelectedRow(), 0));
         }
     });
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Modulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Modulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Modulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Modulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Modulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblModulo;
    // End of variables declaration//GEN-END:variables
}
