/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package control_salones.vista;

import control_salones.controlador.DAO_Especialidad;
import control_salones.controlador.DAO_Instructor;
import control_salones.modelo.Especialidad;
import control_salones.modelo.Instructor;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author efi
 */
public class frmInstructor extends javax.swing.JFrame {

    /**
     * Creates new form frmInstructor
     */
    public frmInstructor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInstructor = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        bntRefrescar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Instructor");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Instructor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 6, -1, -1));

        txtBuscar.setToolTipText("ingrese codigo");
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 280, -1));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/control_salones/media/if_search_322497.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        tblInstructor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInstructor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 82, 720, 270));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/control_salones/media/if_document_text_add_103511.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/control_salones/media/if_notes_edit_103663.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/control_salones/media/if_trash_bin_1370026.png"))); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        bntRefrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/control_salones/media/if_Update_984748.png"))); // NOI18N
        bntRefrescar.setText("Refrescar");
        bntRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRefrescarActionPerformed(evt);
            }
        });
        getContentPane().add(bntRefrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        consultaInstructor();


    }//GEN-LAST:event_formWindowActivated

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        consultaInstructor();
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        frmAddInstructor agregar = new frmAddInstructor();
        agregar.setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        if (tblInstructor.getSelectedRowCount() > 0) {
            frmModificarInstructor modificar = new frmModificarInstructor();
            modificar.txtCodigo.setText(tblInstructor.getValueAt(tblInstructor.getSelectedRow(), 0).toString());
            modificar.txtNombreInstructor.setText(tblInstructor.getValueAt(tblInstructor.getSelectedRow(), 1).toString());
            modificar.txtRenglonPresupuestario.setText(tblInstructor.getValueAt(tblInstructor.getSelectedRow(), 2).toString());
            modificar.txtNitInstructor.setText(tblInstructor.getValueAt(tblInstructor.getSelectedRow(), 4).toString());
            modificar.txtEmail.setText(tblInstructor.getValueAt(tblInstructor.getSelectedRow(), 5).toString());
            modificar.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Debe Seleccionar una fila de la tabla...!");
        }


    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        if (tblInstructor.getSelectedRowCount() > 0) {
            frmEliminarInstructor eliminar = new frmEliminarInstructor();
            eliminar.txtCodigo.setText(tblInstructor.getValueAt(tblInstructor.getSelectedRow(), 0).toString());
            eliminar.txtNombreInstructor.setText(tblInstructor.getValueAt(tblInstructor.getSelectedRow(), 1).toString());
            eliminar.txtRenglonPresupuestario.setText(tblInstructor.getValueAt(tblInstructor.getSelectedRow(), 2).toString());
            eliminar.txtNitInstructor.setText(tblInstructor.getValueAt(tblInstructor.getSelectedRow(), 4).toString());
            eliminar.txtEmail.setText(tblInstructor.getValueAt(tblInstructor.getSelectedRow(), 5).toString());
            eliminar.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Debe Seleccionar una fila de la tabla...!");
        }


    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        DAO_Instructor buscar = new DAO_Instructor();
        buscar.buscarDatos(this.txtBuscar.getText());
        buscar();


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void bntRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRefrescarActionPerformed

        consultaInstructor();

    }//GEN-LAST:event_bntRefrescarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInstructor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntRefrescar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInstructor;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

    public void consultaInstructor() {
        DAO_Instructor cat = new DAO_Instructor();
        Object[] cols = {"codigo", "Nombre_Instructor", "Renglon_Presupuestario", "Estado", "Nit_Instructor", "Correo_Instructor"};
        ArrayList<Instructor> lista = cat.obtenerDatos();
        Object[][] datos = new Object[lista.size()][cols.length];
        int i = 0;
        for (Instructor fila : lista) {
            datos[i][0] = fila.getCodigo();
            datos[i][1] = fila.getNombre_instructor();
            datos[i][2] = fila.getRenglon_presupuestario();
            datos[i][3] = fila.getEstado();
            datos[i][4] = fila.getNit_instructor();
            datos[i][5] = fila.getCorreo_instructor();
            i++;
        }
        DefaultTableModel model = new DefaultTableModel(datos, cols);
        tblInstructor.setModel(model);
    }

    public void buscar() {
        DAO_Instructor cat = new DAO_Instructor();
        Object[] cols = {"codigo", "Nombre_Instructor", "Renglon_Presupuestario", "Estado", "Nit_Instructor", "Correo_Instructor"};
        ArrayList<Instructor> lista = cat.buscarDatos(txtBuscar.getText());
        Object[][] datos = new Object[lista.size()][cols.length];
        int i = 0;
        for (Instructor fila : lista) {
            datos[i][0] = fila.getCodigo();
            datos[i][1] = fila.getNombre_instructor();
            datos[i][2] = fila.getRenglon_presupuestario();
            datos[i][3] = fila.getEstado();
            datos[i][4] = fila.getNit_instructor();
            datos[i][5] = fila.getCorreo_instructor();
            i++;
        }
        DefaultTableModel model = new DefaultTableModel(datos, cols);
        tblInstructor.setModel(model);
    }

}
