/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package control_salones.vista;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.RowSorterEvent;
import javax.swing.event.RowSorterListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author hym
 */
public class JTableWithTittleRowsCols extends javax.swing.JFrame {

    /**
     * Creates new form JTableWithTittleRowsCols
     * 
     */
    private JScrollPane scrollPane;
    private DefaultTableModel model;
    private TableRowSorter<TableModel> sorter;
    private JTable headerTable, table;
    
    
    public JTableWithTittleRowsCols() {
       model = new DefaultTableModel(10, 7){
           @Override
           public boolean isCellEditable(int i, int i1) {
               if( 0 == i1) return false;
               return super.isCellEditable(i, i1); //To change body of generated methods, choose Tools | Templates.
           }
       };
       model.setColumnIdentifiers(new String[]{"","L","M","M","J","V","S","D"});
       for(int i=0; i < 10; i++){
           model.setValueAt(i + 1, i, 0);
       }
       table = new JTable(model){
           @Override
           public void changeSelection(int i, int i1, boolean bln, boolean bln1) {
               if(i1 == 0)
                   super.changeSelection(i, i1 +1, bln, bln1);
               super.changeSelection(i, i1, bln, bln1); //To change body of generated methods, choose Tools | Templates.
           }
           
       };
       table.getColumnModel().getColumn(0).setCellRenderer(table.getTableHeader().getDefaultRenderer());
       this.add(new JScrollPane(table));
       this.pack();
       this.setVisible(true);
       this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       //Arreglo para definir los nombres de las columnas
       String [] columnas = {"Columna 1", "Columna 2", "Columna 3"};
       //arreglo para definir datos, filas y columnas de la tabla
        Object[][] datos = {{1, "dato", false}, // fila uno
                            {2, "dato 2", true}};
       DefaultTableModel model = new DefaultTableModel(datos, columnas);
       table.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JTableWithTittleRowsCols.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JTableWithTittleRowsCols.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JTableWithTittleRowsCols.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JTableWithTittleRowsCols.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTableWithTittleRowsCols().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
